# Generated by Django 4.2.4 on 2023-08-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='ans',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='op4',
        ),
        migrations.RemoveField(
            model_name='quizmodel',
            name='question',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='quiz_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_master.quizmodel')),
            ],
        ),
    ]
