# Generated by Django 4.2.4 on 2023-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0002_remove_quizmodel_ans_remove_quizmodel_op1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='quiz_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
